# fly.toml app configuration file generated for api-hono-young-river-2449 on 2024-09-28T01:40:56+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'api-hono-young-river-2449'
primary_region = 'lax'

[build]

[env]
  PORT = '8080'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1
